ServerEvents.recipes(e => {
    e.remove({output: 'silentgear:template_board'})
    e.shapeless('silentgear:template_board', ['farmersdelight:tree_bark', 'gtceu:sticky_resin', 'gtceu:wood_plate'])
    e.remove({output: '#tools', mod: 'minecraft'})
    e.remove({output: '#forge:armors', mod: 'minecraft'})
    e.remove({output: 'stone_sword'})
    e.remove({output: 'stone_axe'})
    e.remove({output: 'stone_pickaxe'})
    e.remove({output: 'stone_shovel'})
    e.remove({output: 'stone_hoe'})

    let wood = ['oak', 'spruce', 'birch', 'jungle', 'acacia', 'dark_oak']
    function axe(material, output) {
        e.shaped(
            output,
            [
                'MM',
                'MS',
                ' S'
            ],
            {
                M: material,
                S: 'stick'
            }
        )
    }
    function pickaxe(material, output) {
        e.shaped(
            output,
            [
                'MMM',
                ' S ',
                ' S '
            ],
            {
                M: material,
                S: 'stick'
            }
        )
    }
    function sword(material, output) {
        e.shaped(
            output,
            [
                'M',
                'M',
                'S'
            ],
            {
                M: material,
                S: 'stick'
            }
        )
    }
    function hoe(material, output) {
        e.shaped(
            output,
            [
                'MM',
                ' S',
                ' S'
            ],
            {
                M: material,
                S: 'stick'
            }
        )
    }
    function shovel(material, output) {
        e.shaped(
            output,
            [
                'M',
                'S',
                'S'
            ],
            {
                M: material,
                S: 'stick'
            }
        )
    }

    wood.forEach(x => {
            axe(`${x}_planks`, Item.of('silentgear:axe', `{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:axe_head",Item:{Count:1b,id:"silentgear:axe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:wood/${x}",Item:{Count:1b,id:"minecraft:${x}_planks"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks"}}]}}}]},Properties:{HarvestTier:"minecraft:wood",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.2f,"silentgear:charging_value":0.59999996f,"silentgear:durability":59.0f,"silentgear:enchantment_value":15.0f,"silentgear:harvest_speed":2.0f,"silentgear:melee_damage":5.0f,"silentgear:rarity":1.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:flammable"},{Level:1b,Name:"silentgear:jagged"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"axe:axe_head{wood/${x},wood/${x},wood/${x}},rod{wood},"}},SGear_UUID:[I;-1217533548,516244022,-1841961513,1654387168]}`))
            pickaxe(`${x}_planks`, Item.of('silentgear:pickaxe', `{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:pickaxe_head",Item:{Count:1b,id:"silentgear:pickaxe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:wood/${x}",Item:{Count:1b,id:"minecraft:${x}_planks"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks"}}]}}}]},Properties:{HarvestTier:"minecraft:wood",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.8f,"silentgear:charging_value":0.59999996f,"silentgear:durability":59.0f,"silentgear:enchantment_value":15.0f,"silentgear:harvest_speed":2.0f,"silentgear:melee_damage":1.0f,"silentgear:rarity":1.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:flammable"},{Level:1b,Name:"silentgear:jagged"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"pickaxe:pickaxe_head{wood/${x},wood/${x},wood/${x}},rod{wood},"}},SGear_UUID:[I;-719485230,-628734598,-1794726072,-383671269]}`))
            hoe(`${x}_planks`, Item.of('silentgear:hoe', `{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:hoe_head",Item:{Count:1b,id:"silentgear:hoe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:wood/${x}",Item:{Count:1b,id:"minecraft:${x}_planks"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks"}}]}}}]},Properties:{HarvestTier:"minecraft:wood",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.0f,"silentgear:charging_value":0.6f,"silentgear:durability":58.999996f,"silentgear:enchantment_value":15.0f,"silentgear:harvest_speed":2.0f,"silentgear:melee_damage":0.0f,"silentgear:rarity":1.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:flammable"},{Level:1b,Name:"silentgear:jagged"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"hoe:hoe_head{wood/${x},wood/${x}},rod{wood},"}},SGear_UUID:[I;-426164795,-1200666465,-1370098210,-1968049159]}`))
            sword(`${x}_planks`, Item.of('silentgear:sword', `{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:sword_blade",Item:{Count:1b,id:"silentgear:sword_blade",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:wood/${x}",Item:{Count:1b,id:"minecraft:${x}_planks"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks"}}]}}}]},Properties:{HarvestTier:"minecraft:wood",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.4f,"silentgear:charging_value":0.6f,"silentgear:durability":58.999996f,"silentgear:enchantment_value":15.0f,"silentgear:harvest_speed":2.0f,"silentgear:melee_damage":3.0f,"silentgear:rarity":1.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:flammable"},{Level:1b,Name:"silentgear:jagged"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"sword:sword_blade{wood/${x},wood/${x}},rod{wood},"}},SGear_UUID:[I;-1984831752,948454224,-1405008933,1351133046]}`))
            shovel(`${x}_planks`, Item.of('silentgear:shovel', `{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:shovel_head",Item:{Count:1b,id:"silentgear:shovel_head",tag:{CraftedCount:1,Damage:0,Materials:[{ID:"silentgear:wood/${x}",Item:{Count:1b,id:"minecraft:${x}_planks"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks"}}]}}}]},Properties:{HarvestTier:"minecraft:wood",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.0f,"silentgear:charging_value":0.6f,"silentgear:durability":59.0f,"silentgear:enchantment_value":15.0f,"silentgear:harvest_speed":2.0f,"silentgear:melee_damage":1.5f,"silentgear:rarity":1.0f,"silentgear:repair_efficiency":2.0f},Traits:[{Level:1b,Name:"silentgear:flammable"},{Level:1b,Name:"silentgear:jagged"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"shovel:shovel_head{wood/${x}},rod{wood},"}},SGear_UUID:[I;-1292539621,1202865420,-1570112865,-1096877530]}`))
    });

    function tool(mat, sw, a, p, sh, h) {
        sword(mat, sw)
        axe(mat, a)
        pickaxe(mat, p)
        shovel(mat, sh)
        hoe(mat, h)
    }
    function armor(mat, h, c, l, b) {
        e.shaped(
            h,
            [
                'MMM',
                'M M'
            ],
            {M: mat}
        )
        e.shaped(
            c,
            [
                'M M',
                'MMM',
                'MMM'
            ],
            {M: mat}
        )
        e.shaped(
            l,
            [
                'MMM',
                'M M',
                'M M'
            ],
            {M: mat}
        )
        e.shaped(
            b,
            [
                'M M',
                'M M'
            ],
            {M: mat}
        )
    }


    tool('cobblestone', 
        Item.of('silentgear:sword', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:sword_blade",Item:{Count:1b,id:"silentgear:sword_blade",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:stone",Item:{Count:1b,id:"minecraft:cobblestone"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.4f,"silentgear:charging_value":0.5f,"silentgear:durability":130.99998f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":4.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"sword:sword_blade{stone,stone},rod{wood},"}},SGear_UUID:[I;-143213521,1300447831,-1686736600,-708779951]}'),
        Item.of('silentgear:axe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:axe_head",Item:{Count:1b,id:"silentgear:axe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:stone",Item:{Count:1b,id:"minecraft:cobblestone"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.2f,"silentgear:charging_value":0.5f,"silentgear:durability":131.0f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":6.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"axe:axe_head{stone,stone,stone},rod{wood},"}},SGear_UUID:[I;1903934226,-1207022663,-2096076636,638413531]}'),
        Item.of('silentgear:pickaxe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:pickaxe_head",Item:{Count:1b,id:"silentgear:pickaxe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:stone",Item:{Count:1b,id:"minecraft:cobblestone"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.8f,"silentgear:charging_value":0.5f,"silentgear:durability":131.0f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":2.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"pickaxe:pickaxe_head{stone,stone,stone},rod{wood},"}},SGear_UUID:[I;-651633000,2106541908,-1347238453,-2119990960]}'),
        Item.of('silentgear:shovel', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:shovel_head",Item:{Count:1b,id:"silentgear:shovel_head",tag:{CraftedCount:1,Damage:0,Materials:[{ID:"silentgear:stone",Item:{Count:1b,id:"minecraft:cobblestone"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.0f,"silentgear:charging_value":0.5f,"silentgear:durability":131.0f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":2.5f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":2.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"shovel:shovel_head{stone},rod{wood},"}},SGear_UUID:[I;-1277294432,-1127921880,-1866157708,377467865]}'),
        Item.of('silentgear:hoe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:hoe_head",Item:{Count:1b,id:"silentgear:hoe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:stone",Item:{Count:1b,id:"minecraft:cobblestone"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.0f,"silentgear:charging_value":0.5f,"silentgear:durability":130.99998f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":0.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"hoe:hoe_head{stone,stone},rod{wood},"}},SGear_UUID:[I;-782666491,1394885119,-1763885030,-12235565]}')
    )

    tool('cobbled_deepslate', 
        Item.of('silentgear:sword', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:sword_blade",Item:{Count:1b,id:"silentgear:sword_blade",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:stone",Item:{Count:1b,id:"minecraft:cobbled_deepslate"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.4f,"silentgear:charging_value":0.5f,"silentgear:durability":130.99998f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":4.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"sword:sword_blade{stone,stone},rod{wood},"}},SGear_UUID:[I;-143213521,1300447831,-1686736600,-708779951]}'),
        Item.of('silentgear:axe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:axe_head",Item:{Count:1b,id:"silentgear:axe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:stone",Item:{Count:1b,id:"minecraft:cobbled_deepslate"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.2f,"silentgear:charging_value":0.5f,"silentgear:durability":131.0f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":6.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"axe:axe_head{stone,stone,stone},rod{wood},"}},SGear_UUID:[I;1903934226,-1207022663,-2096076636,638413531]}'),
        Item.of('silentgear:pickaxe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:pickaxe_head",Item:{Count:1b,id:"silentgear:pickaxe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:stone",Item:{Count:1b,id:"minecraft:cobbled_deepslate"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.8f,"silentgear:charging_value":0.5f,"silentgear:durability":131.0f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":2.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"pickaxe:pickaxe_head{stone,stone,stone},rod{wood},"}},SGear_UUID:[I;-651633000,2106541908,-1347238453,-2119990960]}'),
        Item.of('silentgear:shovel', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:shovel_head",Item:{Count:1b,id:"silentgear:shovel_head",tag:{CraftedCount:1,Damage:0,Materials:[{ID:"silentgear:stone",Item:{Count:1b,id:"minecraft:cobbled_deepslate"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.0f,"silentgear:charging_value":0.5f,"silentgear:durability":131.0f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":2.5f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":2.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"shovel:shovel_head{stone},rod{wood},"}},SGear_UUID:[I;-1277294432,-1127921880,-1866157708,377467865]}'),
        Item.of('silentgear:hoe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:hoe_head",Item:{Count:1b,id:"silentgear:hoe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:stone",Item:{Count:1b,id:"minecraft:cobbled_deepslate"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.0f,"silentgear:charging_value":0.5f,"silentgear:durability":130.99998f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":0.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"hoe:hoe_head{stone,stone},rod{wood},"}},SGear_UUID:[I;-782666491,1394885119,-1763885030,-12235565]}')
    )
    tool('andesite',
        Item.of('silentgear:sword', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:sword_blade",Item:{Count:1b,id:"silentgear:sword_blade",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:stone/andesite",Item:{Count:1b,id:"minecraft:andesite"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.4f,"silentgear:charging_value":0.5f,"silentgear:durability":130.99998f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":4.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"sword:sword_blade{stone/andesite,stone/andesite},rod{wood},"}},SGear_UUID:[I;-651413154,-1440003649,-2131622428,-1865550491]}'),
        Item.of('silentgear:axe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:axe_head",Item:{Count:1b,id:"silentgear:axe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:stone/andesite",Item:{Count:1b,id:"minecraft:andesite"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.2f,"silentgear:charging_value":0.5f,"silentgear:durability":131.0f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":6.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"axe:axe_head{stone/andesite,stone/andesite,stone/andesite},rod{wood},"}},SGear_UUID:[I;706456636,144457835,-1252259064,1170635844]}'),
        Item.of('silentgear:pickaxe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:pickaxe_head",Item:{Count:1b,id:"silentgear:pickaxe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:stone/andesite",Item:{Count:1b,id:"minecraft:andesite"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.8f,"silentgear:charging_value":0.5f,"silentgear:durability":131.0f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":2.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"pickaxe:pickaxe_head{stone/andesite,stone/andesite,stone/andesite},rod{wood},"}},SGear_UUID:[I;2107259956,-2117121536,-1273470448,-1427910811]}'),
        Item.of('silentgear:shovel', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:shovel_head",Item:{Count:1b,id:"silentgear:shovel_head",tag:{CraftedCount:1,Damage:0,Materials:[{ID:"silentgear:stone/andesite",Item:{Count:1b,id:"minecraft:andesite"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.0f,"silentgear:charging_value":0.5f,"silentgear:durability":131.0f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":2.5f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":2.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"shovel:shovel_head{stone/andesite},rod{wood},"}},SGear_UUID:[I;909083073,-1630977312,-1582650313,69610206]}'),
        Item.of('silentgear:hoe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:hoe_head",Item:{Count:1b,id:"silentgear:hoe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:stone/andesite",Item:{Count:1b,id:"minecraft:andesite"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.0f,"silentgear:charging_value":0.5f,"silentgear:durability":130.99998f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":0.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"hoe:hoe_head{stone/andesite,stone/andesite},rod{wood},"}},SGear_UUID:[I;-1897721612,-1208791205,-2064141028,-617495536]}')
    )
    tool('diorite',
        Item.of('silentgear:sword', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:sword_blade",Item:{Count:1b,id:"silentgear:sword_blade",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:stone/diorite",Item:{Count:1b,id:"minecraft:diorite"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.4f,"silentgear:charging_value":0.5f,"silentgear:durability":130.99998f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":4.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"sword:sword_blade{stone/diorite,stone/diorite},rod{wood},"}},SGear_UUID:[I;-2107900776,-1198961773,-1977618001,1848247871]}'),
        Item.of('silentgear:axe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:axe_head",Item:{Count:1b,id:"silentgear:axe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:stone/diorite",Item:{Count:1b,id:"minecraft:diorite"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.2f,"silentgear:charging_value":0.5f,"silentgear:durability":131.0f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":6.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"axe:axe_head{stone/diorite,stone/diorite,stone/diorite},rod{wood},"}},SGear_UUID:[I;1659284466,1919371922,-1270891019,66784262]}'),
        Item.of('silentgear:pickaxe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:pickaxe_head",Item:{Count:1b,id:"silentgear:pickaxe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:stone/diorite",Item:{Count:1b,id:"minecraft:diorite"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.8f,"silentgear:charging_value":0.5f,"silentgear:durability":131.0f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":2.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"pickaxe:pickaxe_head{stone/diorite,stone/diorite,stone/diorite},rod{wood},"}},SGear_UUID:[I;-1222889490,-47496752,-2036683817,1236376514]}'),
        Item.of('silentgear:shovel', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:shovel_head",Item:{Count:1b,id:"silentgear:shovel_head",tag:{CraftedCount:1,Damage:0,Materials:[{ID:"silentgear:stone/diorite",Item:{Count:1b,id:"minecraft:diorite"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.0f,"silentgear:charging_value":0.5f,"silentgear:durability":131.0f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":2.5f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":2.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"shovel:shovel_head{stone/diorite},rod{wood},"}},SGear_UUID:[I;-480511831,-1000062214,-2042961540,1604226850]}'),
        Item.of('silentgear:hoe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:hoe_head",Item:{Count:1b,id:"silentgear:hoe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:stone/diorite",Item:{Count:1b,id:"minecraft:diorite"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.0f,"silentgear:charging_value":0.5f,"silentgear:durability":130.99998f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":0.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"hoe:hoe_head{stone/diorite,stone/diorite},rod{wood},"}},SGear_UUID:[I;1867620143,-589214890,-1166587505,1024294815]}')
    )
    tool('granite',
        Item.of('silentgear:sword', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:sword_blade",Item:{Count:1b,id:"silentgear:sword_blade",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:stone/granite",Item:{Count:1b,id:"minecraft:granite"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.4f,"silentgear:charging_value":0.5f,"silentgear:durability":130.99998f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":4.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"sword:sword_blade{stone/granite,stone/granite},rod{wood},"}},SGear_UUID:[I;-872121034,406800268,-2073234755,854042503]}'),
        Item.of('silentgear:axe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:axe_head",Item:{Count:1b,id:"silentgear:axe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:stone/granite",Item:{Count:1b,id:"minecraft:granite"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.2f,"silentgear:charging_value":0.5f,"silentgear:durability":131.0f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":6.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"axe:axe_head{stone/granite,stone/granite,stone/granite},rod{wood},"}},SGear_UUID:[I;74209420,1833585528,-1807663463,2039358037]}'),
        Item.of('silentgear:pickaxe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:pickaxe_head",Item:{Count:1b,id:"silentgear:pickaxe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:stone/granite",Item:{Count:1b,id:"minecraft:granite"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.8f,"silentgear:charging_value":0.5f,"silentgear:durability":131.0f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":2.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"pickaxe:pickaxe_head{stone/granite,stone/granite,stone/granite},rod{wood},"}},SGear_UUID:[I;2079020640,-908963983,-1603493265,-897459846]}'),
        Item.of('silentgear:shovel', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:shovel_head",Item:{Count:1b,id:"silentgear:shovel_head",tag:{CraftedCount:1,Damage:0,Materials:[{ID:"silentgear:stone/granite",Item:{Count:1b,id:"minecraft:granite"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.0f,"silentgear:charging_value":0.5f,"silentgear:durability":131.0f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":2.5f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":2.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"shovel:shovel_head{stone/granite},rod{wood},"}},SGear_UUID:[I;1950536398,968509997,-1417452373,-1791706452]}'),
        Item.of('silentgear:hoe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:hoe_head",Item:{Count:1b,id:"silentgear:hoe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:stone/granite",Item:{Count:1b,id:"minecraft:granite"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.0f,"silentgear:charging_value":0.5f,"silentgear:durability":130.99998f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":0.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"hoe:hoe_head{stone/granite,stone/granite},rod{wood},"}},SGear_UUID:[I;-1231934327,476594295,-1289094450,-1503701536]}')
    )
    tool('mossy_cobblestone', 
        Item.of('silentgear:sword', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:sword_blade",Item:{Count:1b,id:"silentgear:sword_blade",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:stone",Item:{Count:1b,id:"minecraft:mossy_cobblestone"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.4f,"silentgear:charging_value":0.5f,"silentgear:durability":130.99998f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":4.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"sword:sword_blade{stone,stone},rod{wood},"}},SGear_UUID:[I;-143213521,1300447831,-1686736600,-708779951]}'),
        Item.of('silentgear:axe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:axe_head",Item:{Count:1b,id:"silentgear:axe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:stone",Item:{Count:1b,id:"minecraft:mossy_cobblestone"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.2f,"silentgear:charging_value":0.5f,"silentgear:durability":131.0f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":6.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"axe:axe_head{stone,stone,stone},rod{wood},"}},SGear_UUID:[I;1903934226,-1207022663,-2096076636,638413531]}'),
        Item.of('silentgear:pickaxe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:pickaxe_head",Item:{Count:1b,id:"silentgear:pickaxe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:stone",Item:{Count:1b,id:"minecraft:mossy_cobblestone"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.8f,"silentgear:charging_value":0.5f,"silentgear:durability":131.0f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":2.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"pickaxe:pickaxe_head{stone,stone,stone},rod{wood},"}},SGear_UUID:[I;-651633000,2106541908,-1347238453,-2119990960]}'),
        Item.of('silentgear:shovel', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:shovel_head",Item:{Count:1b,id:"silentgear:shovel_head",tag:{CraftedCount:1,Damage:0,Materials:[{ID:"silentgear:stone",Item:{Count:1b,id:"minecraft:mossy_cobblestone"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.0f,"silentgear:charging_value":0.5f,"silentgear:durability":131.0f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":2.5f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":2.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"shovel:shovel_head{stone},rod{wood},"}},SGear_UUID:[I;-1277294432,-1127921880,-1866157708,377467865]}'),
        Item.of('silentgear:hoe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:hoe_head",Item:{Count:1b,id:"silentgear:hoe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:stone",Item:{Count:1b,id:"minecraft:mossy_cobblestone"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.0f,"silentgear:charging_value":0.5f,"silentgear:durability":130.99998f,"silentgear:enchantment_value":5.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":0.0f,"silentgear:rarity":4.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:ancient"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"hoe:hoe_head{stone,stone},rod{wood},"}},SGear_UUID:[I;-782666491,1394885119,-1763885030,-12235565]}')
    )
    tool('blackstone',
        Item.of('silentgear:sword', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:sword_blade",Item:{Count:1b,id:"silentgear:sword_blade",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:blackstone",Item:{Count:1b,id:"minecraft:blackstone"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.4f,"silentgear:charging_value":0.6f,"silentgear:durability":151.0f,"silentgear:enchantment_value":4.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":4.0f,"silentgear:rarity":8.999999f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:brittle"},{Level:2b,Name:"silentgear:jagged"},{Level:2b,Name:"silentgear:hard"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"sword:sword_blade{blackstone,blackstone},rod{wood},"}},SGear_UUID:[I;-1848356762,-1538962555,-1686639587,953662975]}'),
        Item.of('silentgear:axe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:axe_head",Item:{Count:1b,id:"silentgear:axe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:blackstone",Item:{Count:1b,id:"minecraft:blackstone"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.2f,"silentgear:charging_value":0.59999996f,"silentgear:durability":151.0f,"silentgear:enchantment_value":4.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":6.0f,"silentgear:rarity":8.999999f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:brittle"},{Level:2b,Name:"silentgear:jagged"},{Level:2b,Name:"silentgear:hard"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"axe:axe_head{blackstone,blackstone,blackstone},rod{wood},"}},SGear_UUID:[I;-1327530762,-1026798480,-1752518664,629932449]}'),
        Item.of('silentgear:pickaxe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:pickaxe_head",Item:{Count:1b,id:"silentgear:pickaxe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:blackstone",Item:{Count:1b,id:"minecraft:blackstone"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.8f,"silentgear:charging_value":0.59999996f,"silentgear:durability":151.0f,"silentgear:enchantment_value":4.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":2.0f,"silentgear:rarity":8.999999f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:brittle"},{Level:2b,Name:"silentgear:jagged"},{Level:2b,Name:"silentgear:hard"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"pickaxe:pickaxe_head{blackstone,blackstone,blackstone},rod{wood},"}},SGear_UUID:[I;2014735962,-2116992596,-2038154366,-602295875]}'),
        Item.of('silentgear:shovel', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:shovel_head",Item:{Count:1b,id:"silentgear:shovel_head",tag:{CraftedCount:1,Damage:0,Materials:[{ID:"silentgear:blackstone",Item:{Count:1b,id:"minecraft:blackstone"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.0f,"silentgear:charging_value":0.6f,"silentgear:durability":151.0f,"silentgear:enchantment_value":4.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":2.5f,"silentgear:rarity":9.0f,"silentgear:repair_efficiency":2.0f},Traits:[{Level:1b,Name:"silentgear:brittle"},{Level:2b,Name:"silentgear:jagged"},{Level:2b,Name:"silentgear:hard"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"shovel:shovel_head{blackstone},rod{wood},"}},SGear_UUID:[I;-1672585808,1865436666,-1423772728,-145937745]}'),
        Item.of('silentgear:hoe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:hoe_head",Item:{Count:1b,id:"silentgear:hoe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:blackstone",Item:{Count:1b,id:"minecraft:blackstone"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:stone",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.0f,"silentgear:charging_value":0.6f,"silentgear:durability":151.0f,"silentgear:enchantment_value":4.0f,"silentgear:harvest_speed":4.0f,"silentgear:melee_damage":0.0f,"silentgear:rarity":8.999999f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:brittle"},{Level:2b,Name:"silentgear:jagged"},{Level:2b,Name:"silentgear:hard"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"hoe:hoe_head{blackstone,blackstone},rod{wood},"}},SGear_UUID:[I;1944976716,-1156101912,-2143777567,948861750]}')
    )
    tool('iron_ingot',
        Item.of('silentgear:sword', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:sword_blade",Item:{Count:1b,id:"silentgear:sword_blade",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:iron",Item:{Count:1b,id:"minecraft:iron_ingot"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:iron",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.4f,"silentgear:charging_value":0.6999999f,"silentgear:durability":249.99998f,"silentgear:enchantment_value":13.999999f,"silentgear:harvest_speed":5.9999995f,"silentgear:magic_damage":1.0f,"silentgear:melee_damage":5.0f,"silentgear:rarity":20.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:3b,Name:"silentgear:malleable"},{Level:1b,Name:"silentgear:magnetic"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:3,ModelKey:"sword:sword_blade{iron,iron},rod{wood},"}},SGear_UUID:[I;591241680,-648524226,-1998646133,-558286627]}'),
        Item.of('silentgear:axe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:axe_head",Item:{Count:1b,id:"silentgear:axe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:iron",Item:{Count:1b,id:"minecraft:iron_ingot"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:iron",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.1f,"silentgear:charging_value":0.6999999f,"silentgear:durability":249.99998f,"silentgear:enchantment_value":13.999999f,"silentgear:harvest_speed":6.0f,"silentgear:magic_damage":1.0f,"silentgear:melee_damage":7.0f,"silentgear:rarity":20.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:3b,Name:"silentgear:malleable"},{Level:1b,Name:"silentgear:magnetic"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:3,ModelKey:"axe:axe_head{iron,iron,iron},rod{wood},"}},SGear_UUID:[I;-915620970,1294616908,-1845270903,-396396434]}'),
        Item.of('silentgear:pickaxe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:pickaxe_head",Item:{Count:1b,id:"silentgear:pickaxe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:iron",Item:{Count:1b,id:"minecraft:iron_ingot"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:iron",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.8f,"silentgear:charging_value":0.6999999f,"silentgear:durability":249.99998f,"silentgear:enchantment_value":13.999999f,"silentgear:harvest_speed":6.0f,"silentgear:magic_damage":1.0f,"silentgear:melee_damage":3.0f,"silentgear:rarity":20.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:3b,Name:"silentgear:malleable"},{Level:1b,Name:"silentgear:magnetic"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:3,ModelKey:"pickaxe:pickaxe_head{iron,iron,iron},rod{wood},"}},SGear_UUID:[I;-689726259,-1759821155,-1889947136,-922131591]}'),
        Item.of('silentgear:shovel', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:shovel_head",Item:{Count:1b,id:"silentgear:shovel_head",tag:{CraftedCount:1,Damage:0,Materials:[{ID:"silentgear:iron",Item:{Count:1b,id:"minecraft:iron_ingot"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:iron",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.0f,"silentgear:charging_value":0.7f,"silentgear:durability":250.0f,"silentgear:enchantment_value":14.0f,"silentgear:harvest_speed":6.0f,"silentgear:magic_damage":1.0f,"silentgear:melee_damage":3.5f,"silentgear:rarity":20.0f,"silentgear:repair_efficiency":2.0f},Traits:[{Level:3b,Name:"silentgear:malleable"},{Level:1b,Name:"silentgear:magnetic"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:3,ModelKey:"shovel:shovel_head{iron},rod{wood},"}},SGear_UUID:[I;334581964,705250267,-1371321907,-671967067]}'),
        Item.of('silentgear:hoe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:hoe_head",Item:{Count:1b,id:"silentgear:hoe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:iron",Item:{Count:1b,id:"minecraft:iron_ingot"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:iron",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-1.0f,"silentgear:charging_value":0.6999999f,"silentgear:durability":249.99998f,"silentgear:enchantment_value":13.999999f,"silentgear:harvest_speed":5.9999995f,"silentgear:magic_damage":1.0f,"silentgear:melee_damage":0.0f,"silentgear:rarity":20.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:3b,Name:"silentgear:malleable"},{Level:1b,Name:"silentgear:magnetic"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:3,ModelKey:"hoe:hoe_head{iron,iron},rod{wood},"}},SGear_UUID:[I;-1717499977,-118665342,-1274890681,145385123]}')
    )
    tool('gold_ingot',
        Item.of('silentgear:sword', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:sword_blade",Item:{Count:1b,id:"silentgear:sword_blade",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:gold",Item:{Count:1b,id:"minecraft:gold_ingot"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:gold",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.4f,"silentgear:charging_value":1.2f,"silentgear:durability":32.0f,"silentgear:enchantment_value":22.0f,"silentgear:harvest_speed":11.999999f,"silentgear:magic_damage":4.0f,"silentgear:melee_damage":3.0f,"silentgear:rarity":50.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:brilliant"},{Level:1b,Name:"silentgear:malleable"},{Level:3b,Name:"silentgear:soft"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:3,ModelKey:"sword:sword_blade{gold,gold},rod{wood},"}},SGear_UUID:[I;1540404543,-1429650509,-1143569257,-1855925726]}'),
        Item.of('silentgear:axe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:axe_head",Item:{Count:1b,id:"silentgear:axe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:gold",Item:{Count:1b,id:"minecraft:gold_ingot"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:gold",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.0f,"silentgear:charging_value":1.1999999f,"silentgear:durability":32.0f,"silentgear:enchantment_value":22.0f,"silentgear:harvest_speed":12.0f,"silentgear:magic_damage":4.0f,"silentgear:melee_damage":5.0f,"silentgear:rarity":50.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:brilliant"},{Level:1b,Name:"silentgear:malleable"},{Level:3b,Name:"silentgear:soft"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:3,ModelKey:"axe:axe_head{gold,gold,gold},rod{wood},"}},SGear_UUID:[I;-2101743680,-1434304509,-1383681569,1328161216]}'),
        Item.of('silentgear:pickaxe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:pickaxe_head",Item:{Count:1b,id:"silentgear:pickaxe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:gold",Item:{Count:1b,id:"minecraft:gold_ingot"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:gold",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.8f,"silentgear:charging_value":1.1999999f,"silentgear:durability":32.0f,"silentgear:enchantment_value":22.0f,"silentgear:harvest_speed":12.0f,"silentgear:magic_damage":4.0f,"silentgear:melee_damage":1.0f,"silentgear:rarity":50.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:brilliant"},{Level:1b,Name:"silentgear:malleable"},{Level:3b,Name:"silentgear:soft"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:3,ModelKey:"pickaxe:pickaxe_head{gold,gold,gold},rod{wood},"}},SGear_UUID:[I;1515775819,-1826142955,-1843357432,-2022209557]}'),
        Item.of('silentgear:shovel', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:shovel_head",Item:{Count:1b,id:"silentgear:shovel_head",tag:{CraftedCount:1,Damage:0,Materials:[{ID:"silentgear:gold",Item:{Count:1b,id:"minecraft:gold_ingot"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:gold",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.0f,"silentgear:charging_value":1.2f,"silentgear:durability":32.0f,"silentgear:enchantment_value":22.0f,"silentgear:harvest_speed":12.0f,"silentgear:magic_damage":4.0f,"silentgear:melee_damage":1.5f,"silentgear:rarity":50.0f,"silentgear:repair_efficiency":2.0f},Traits:[{Level:1b,Name:"silentgear:brilliant"},{Level:1b,Name:"silentgear:malleable"},{Level:3b,Name:"silentgear:soft"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:3,ModelKey:"shovel:shovel_head{gold},rod{wood},"}},SGear_UUID:[I;-294494218,-1314566986,-1331960794,727111836]}'),
        Item.of('silentgear:hoe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:hoe_head",Item:{Count:1b,id:"silentgear:hoe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:gold",Item:{Count:1b,id:"minecraft:gold_ingot"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:gold",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.0f,"silentgear:charging_value":1.2f,"silentgear:durability":32.0f,"silentgear:enchantment_value":22.0f,"silentgear:harvest_speed":11.999999f,"silentgear:magic_damage":4.0f,"silentgear:melee_damage":0.0f,"silentgear:rarity":50.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:brilliant"},{Level:1b,Name:"silentgear:malleable"},{Level:3b,Name:"silentgear:soft"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:3,ModelKey:"hoe:hoe_head{gold,gold},rod{wood},"}},SGear_UUID:[I;-2066675479,-1195684026,-1983336357,613006210]}')
    )
    tool('diamond',
        Item.of('silentgear:sword', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:sword_blade",Item:{Count:1b,id:"silentgear:sword_blade",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:diamond",Item:{Count:1b,id:"minecraft:diamond"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:diamond",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.4f,"silentgear:charging_value":0.8f,"silentgear:durability":1561.0f,"silentgear:enchantment_value":10.0f,"silentgear:harvest_speed":8.0f,"silentgear:magic_damage":1.0f,"silentgear:melee_damage":6.0f,"silentgear:rarity":70.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:2b,Name:"silentgear:brittle"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:3,ModelKey:"sword:sword_blade{diamond,diamond},rod{wood},"}},SGear_UUID:[I;-1368003102,709510240,-1842095835,1856274159]}'),
        Item.of('silentgear:axe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:axe_head",Item:{Count:1b,id:"silentgear:axe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:diamond",Item:{Count:1b,id:"minecraft:diamond"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:diamond",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.0f,"silentgear:charging_value":0.8f,"silentgear:durability":1561.0f,"silentgear:enchantment_value":10.0f,"silentgear:harvest_speed":8.0f,"silentgear:magic_damage":1.0f,"silentgear:melee_damage":8.0f,"silentgear:rarity":69.99999f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:2b,Name:"silentgear:brittle"},{Level:1b,Name:"silentgear:lustrous"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:3,ModelKey:"axe:axe_head{diamond,diamond,diamond},rod{wood},"}},SGear_UUID:[I;435060493,1479231326,-2044107222,1650416049]}'),
        Item.of('silentgear:pickaxe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:pickaxe_head",Item:{Count:1b,id:"silentgear:pickaxe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:3b,ID:"silentgear:diamond",Item:{Count:1b,id:"minecraft:diamond"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:diamond",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-2.8f,"silentgear:charging_value":0.8f,"silentgear:durability":1561.0f,"silentgear:enchantment_value":10.0f,"silentgear:harvest_speed":8.0f,"silentgear:magic_damage":1.0f,"silentgear:melee_damage":4.0f,"silentgear:rarity":69.99999f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:2b,Name:"silentgear:brittle"},{Level:1b,Name:"silentgear:lustrous"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:3,ModelKey:"pickaxe:pickaxe_head{diamond,diamond,diamond},rod{wood},"}},SGear_UUID:[I;-168817881,-1106162865,-1767315161,-1117925947]}'),
        Item.of('silentgear:shovel', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:shovel_head",Item:{Count:1b,id:"silentgear:shovel_head",tag:{CraftedCount:1,Damage:0,Materials:[{ID:"silentgear:diamond",Item:{Count:1b,id:"minecraft:diamond"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:diamond",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":-3.0f,"silentgear:charging_value":0.8f,"silentgear:durability":1561.0f,"silentgear:enchantment_value":10.0f,"silentgear:harvest_speed":8.0f,"silentgear:magic_damage":1.0f,"silentgear:melee_damage":4.5f,"silentgear:rarity":70.0f,"silentgear:repair_efficiency":2.0f},Traits:[{Level:2b,Name:"silentgear:brittle"},{Level:1b,Name:"silentgear:lustrous"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:3,ModelKey:"shovel:shovel_head{diamond},rod{wood},"}},SGear_UUID:[I;293576161,1889355595,-1535979818,-2084442790]}'),
        Item.of('silentgear:hoe', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:hoe_head",Item:{Count:1b,id:"silentgear:hoe_head",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:diamond",Item:{Count:1b,id:"minecraft:diamond"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:diamond",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":0.0f,"silentgear:charging_value":0.8f,"silentgear:durability":1561.0f,"silentgear:enchantment_value":10.0f,"silentgear:harvest_speed":8.0f,"silentgear:magic_damage":1.0f,"silentgear:melee_damage":0.0f,"silentgear:rarity":70.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:2b,Name:"silentgear:brittle"},{Level:1b,Name:"silentgear:lustrous"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:3,ModelKey:"hoe:hoe_head{diamond,diamond},rod{wood},"}},SGear_UUID:[I;-1999004466,20006476,-1380659949,-111560498]}')
    )
    armor('iron_ingot',
        Item.of('silentgear:helmet', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:helmet_plates",Item:{Count:1b,id:"silentgear:helmet_plates",tag:{CraftedCount:1,Damage:0,Materials:[{Count:5b,ID:"silentgear:iron",Item:{Count:1b,id:"minecraft:iron_ingot"}}]}}}]},Properties:{HarvestTier:"minecraft:iron",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:armor":2.0f,"silentgear:armor_durability":15.000001f,"silentgear:armor_toughness":0.0f,"silentgear:charging_value":0.7f,"silentgear:durability":250.0f,"silentgear:enchantment_value":14.000001f,"silentgear:knockback_resistance":0.0f,"silentgear:magic_armor":1.5f,"silentgear:projectile_accuracy":1.1f,"silentgear:projectile_speed":1.0f,"silentgear:rarity":20.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:3b,Name:"silentgear:malleable"},{Level:1b,Name:"silentgear:magnetic"}]},Rendering:{Model:3,ModelKey:"helmet:helmet_plates{iron,iron,iron,iron,iron},"}},SGear_UUID:[I;1528549060,1602308706,-1320200198,116234330]}'),
        Item.of('silentgear:chestplate', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:chestplate_plates",Item:{Count:1b,id:"silentgear:chestplate_plates",tag:{CraftedCount:1,Damage:0,Materials:[{Count:8b,ID:"silentgear:iron",Item:{Count:1b,id:"minecraft:iron_ingot"}}]}}}]},Properties:{HarvestTier:"minecraft:iron",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:armor":5.9999995f,"silentgear:armor_durability":15.0f,"silentgear:armor_toughness":0.0f,"silentgear:charging_value":0.7f,"silentgear:durability":250.0f,"silentgear:enchantment_value":14.0f,"silentgear:knockback_resistance":0.0f,"silentgear:magic_armor":1.4999999f,"silentgear:projectile_accuracy":1.1f,"silentgear:projectile_speed":1.0f,"silentgear:rarity":20.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:3b,Name:"silentgear:malleable"},{Level:1b,Name:"silentgear:magnetic"}]},Rendering:{Model:3,ModelKey:"chestplate:chestplate_plates{iron,iron,iron,iron,iron,iron,iron,iron},"}},SGear_UUID:[I;-989097081,5459556,-1573655826,205063676]}'),
        Item.of('silentgear:leggings', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:legging_plates",Item:{Count:1b,id:"silentgear:legging_plates",tag:{CraftedCount:1,Damage:0,Materials:[{Count:7b,ID:"silentgear:iron",Item:{Count:1b,id:"minecraft:iron_ingot"}}]}}}]},Properties:{HarvestTier:"minecraft:iron",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:armor":5.0f,"silentgear:armor_durability":15.000001f,"silentgear:armor_toughness":0.0f,"silentgear:charging_value":0.70000005f,"silentgear:durability":250.0f,"silentgear:enchantment_value":14.0f,"silentgear:knockback_resistance":0.0f,"silentgear:magic_armor":1.4999999f,"silentgear:projectile_accuracy":1.1000001f,"silentgear:projectile_speed":1.0f,"silentgear:rarity":20.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:3b,Name:"silentgear:malleable"},{Level:1b,Name:"silentgear:magnetic"}]},Rendering:{Model:3,ModelKey:"leggings:legging_plates{iron,iron,iron,iron,iron,iron,iron},"}},SGear_UUID:[I;-1565741476,-975549492,-2059860682,-1460317767]}'),
        Item.of('silentgear:boots', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:boot_plates",Item:{Count:1b,id:"silentgear:boot_plates",tag:{CraftedCount:1,Damage:0,Materials:[{Count:4b,ID:"silentgear:iron",Item:{Count:1b,id:"minecraft:iron_ingot"}}]}}}]},Properties:{HarvestTier:"minecraft:iron",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:armor":2.0f,"silentgear:armor_durability":15.000001f,"silentgear:armor_toughness":0.0f,"silentgear:charging_value":0.7f,"silentgear:durability":250.0f,"silentgear:enchantment_value":14.000001f,"silentgear:knockback_resistance":0.0f,"silentgear:magic_armor":1.5f,"silentgear:projectile_accuracy":1.1f,"silentgear:projectile_speed":1.0f,"silentgear:rarity":20.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:3b,Name:"silentgear:malleable"},{Level:1b,Name:"silentgear:magnetic"}]},Rendering:{Model:3,ModelKey:"boots:boot_plates{iron,iron,iron,iron},"}},SGear_UUID:[I;666901832,-1004319120,-1531210068,-730405103]}')
    )
    armor('gold_ingot',
        Item.of('silentgear:helmet', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:helmet_plates",Item:{Count:1b,id:"silentgear:helmet_plates",tag:{CraftedCount:1,Damage:0,Materials:[{Count:5b,ID:"silentgear:gold",Item:{Count:1b,id:"minecraft:gold_ingot"}}]}}}]},Properties:{HarvestTier:"minecraft:gold",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:armor":2.0f,"silentgear:armor_durability":7.0000005f,"silentgear:armor_toughness":0.0f,"silentgear:charging_value":1.1999999f,"silentgear:durability":32.0f,"silentgear:enchantment_value":22.000002f,"silentgear:knockback_resistance":0.0f,"silentgear:magic_armor":2.0f,"silentgear:projectile_accuracy":1.0f,"silentgear:projectile_speed":1.1f,"silentgear:rarity":50.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:brilliant"},{Level:1b,Name:"silentgear:malleable"}]},Rendering:{Model:3,ModelKey:"helmet:helmet_plates{gold,gold,gold,gold,gold},"}},SGear_UUID:[I;-82076871,1785285870,-1378356391,-2124426558]}'),
        Item.of('silentgear:chestplate', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:chestplate_plates",Item:{Count:1b,id:"silentgear:chestplate_plates",tag:{CraftedCount:1,Damage:0,Materials:[{Count:8b,ID:"silentgear:gold",Item:{Count:1b,id:"minecraft:gold_ingot"}}]}}}]},Properties:{HarvestTier:"minecraft:gold",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:armor":5.0f,"silentgear:armor_durability":7.0f,"silentgear:armor_toughness":0.0f,"silentgear:charging_value":1.1999999f,"silentgear:durability":32.0f,"silentgear:enchantment_value":22.0f,"silentgear:knockback_resistance":0.0f,"silentgear:magic_armor":2.0f,"silentgear:projectile_accuracy":1.0f,"silentgear:projectile_speed":1.1f,"silentgear:rarity":50.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:brilliant"},{Level:1b,Name:"silentgear:malleable"}]},Rendering:{Model:3,ModelKey:"chestplate:chestplate_plates{gold,gold,gold,gold,gold,gold,gold,gold},"}},SGear_UUID:[I;-1391966042,692994477,-1191422296,-1778078964]}'),
        Item.of('silentgear:leggings', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:legging_plates",Item:{Count:1b,id:"silentgear:legging_plates",tag:{CraftedCount:1,Damage:0,Materials:[{Count:7b,ID:"silentgear:gold",Item:{Count:1b,id:"minecraft:gold_ingot"}}]}}}]},Properties:{HarvestTier:"minecraft:gold",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:armor":2.9999998f,"silentgear:armor_durability":7.0f,"silentgear:armor_toughness":0.0f,"silentgear:charging_value":1.1999999f,"silentgear:durability":32.0f,"silentgear:enchantment_value":22.0f,"silentgear:knockback_resistance":0.0f,"silentgear:magic_armor":2.0f,"silentgear:projectile_accuracy":1.0f,"silentgear:projectile_speed":1.1000001f,"silentgear:rarity":50.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:brilliant"},{Level:1b,Name:"silentgear:malleable"}]},Rendering:{Model:3,ModelKey:"leggings:legging_plates{gold,gold,gold,gold,gold,gold,gold},"}},SGear_UUID:[I;-1580271097,-200454675,-1930711583,149113250]}'),
        Item.of('silentgear:boots', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:boot_plates",Item:{Count:1b,id:"silentgear:boot_plates",tag:{CraftedCount:1,Damage:0,Materials:[{Count:4b,ID:"silentgear:gold",Item:{Count:1b,id:"minecraft:gold_ingot"}}]}}}]},Properties:{HarvestTier:"minecraft:gold",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:armor":1.0f,"silentgear:armor_durability":7.0000005f,"silentgear:armor_toughness":0.0f,"silentgear:charging_value":1.1999999f,"silentgear:durability":32.0f,"silentgear:enchantment_value":22.000002f,"silentgear:knockback_resistance":0.0f,"silentgear:magic_armor":2.0f,"silentgear:projectile_accuracy":1.0f,"silentgear:projectile_speed":1.1f,"silentgear:rarity":50.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:brilliant"},{Level:1b,Name:"silentgear:malleable"}]},Rendering:{Model:3,ModelKey:"boots:boot_plates{gold,gold,gold,gold},"}},SGear_UUID:[I;119739317,-126729557,-2088048139,-603021327]}')
    )
    armor('diamond',
        Item.of('silentgear:helmet', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:helmet_plates",Item:{Count:1b,id:"silentgear:helmet_plates",tag:{CraftedCount:1,Damage:0,Materials:[{Count:5b,ID:"silentgear:diamond",Item:{Count:1b,id:"minecraft:diamond"}}]}}}]},Properties:{HarvestTier:"minecraft:diamond",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:armor":3.0f,"silentgear:armor_durability":33.0f,"silentgear:armor_toughness":2.0f,"silentgear:charging_value":0.8000001f,"silentgear:durability":1561.0f,"silentgear:enchantment_value":10.0f,"silentgear:knockback_resistance":0.0f,"silentgear:magic_armor":1.0f,"silentgear:projectile_accuracy":1.1f,"silentgear:projectile_speed":0.8999999f,"silentgear:rarity":70.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:2b,Name:"silentgear:brittle"}]},Rendering:{Model:3,ModelKey:"helmet:helmet_plates{diamond,diamond,diamond,diamond,diamond},"}},SGear_UUID:[I;-1844260460,1429947639,-1153483369,115320988]}'),
        Item.of('silentgear:chestplate', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:chestplate_plates",Item:{Count:1b,id:"silentgear:chestplate_plates",tag:{CraftedCount:1,Damage:0,Materials:[{Count:8b,ID:"silentgear:diamond",Item:{Count:1b,id:"minecraft:diamond"}}]}}}]},Properties:{HarvestTier:"minecraft:diamond",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:armor":8.0f,"silentgear:armor_durability":33.0f,"silentgear:armor_toughness":2.0f,"silentgear:charging_value":0.8f,"silentgear:durability":1560.9999f,"silentgear:enchantment_value":10.0f,"silentgear:knockback_resistance":0.0f,"silentgear:magic_armor":1.0f,"silentgear:projectile_accuracy":1.1f,"silentgear:projectile_speed":0.9f,"silentgear:rarity":70.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:2b,Name:"silentgear:brittle"}]},Rendering:{Model:3,ModelKey:"chestplate:chestplate_plates{diamond,diamond,diamond,diamond,diamond,diamond,diamond,diamond},"}},SGear_UUID:[I;1545032371,224609171,-1496767537,1145332343]}'),
        Item.of('silentgear:leggings', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:legging_plates",Item:{Count:1b,id:"silentgear:legging_plates",tag:{CraftedCount:1,Damage:0,Materials:[{Count:7b,ID:"silentgear:diamond",Item:{Count:1b,id:"minecraft:diamond"}}]}}}]},Properties:{HarvestTier:"minecraft:diamond",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:armor":5.9999995f,"silentgear:armor_durability":33.0f,"silentgear:armor_toughness":2.0f,"silentgear:charging_value":0.8f,"silentgear:durability":1561.0f,"silentgear:enchantment_value":10.0f,"silentgear:knockback_resistance":0.0f,"silentgear:magic_armor":1.0f,"silentgear:projectile_accuracy":1.1000001f,"silentgear:projectile_speed":0.9f,"silentgear:rarity":70.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:2b,Name:"silentgear:brittle"}]},Rendering:{Model:3,ModelKey:"leggings:legging_plates{diamond,diamond,diamond,diamond,diamond,diamond,diamond},"}},SGear_UUID:[I;1095009540,-1169209107,-1281302095,607566496]}'),
        Item.of('silentgear:boots', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:boot_plates",Item:{Count:1b,id:"silentgear:boot_plates",tag:{CraftedCount:1,Damage:0,Materials:[{Count:4b,ID:"silentgear:diamond",Item:{Count:1b,id:"minecraft:diamond"}}]}}}]},Properties:{HarvestTier:"minecraft:diamond",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:armor":3.0f,"silentgear:armor_durability":33.0f,"silentgear:armor_toughness":2.0f,"silentgear:charging_value":0.8f,"silentgear:durability":1561.0f,"silentgear:enchantment_value":10.0f,"silentgear:knockback_resistance":0.0f,"silentgear:magic_armor":1.0f,"silentgear:projectile_accuracy":1.1f,"silentgear:projectile_speed":0.9f,"silentgear:rarity":70.0f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:2b,Name:"silentgear:brittle"}]},Rendering:{Model:3,ModelKey:"boots:boot_plates{diamond,diamond,diamond,diamond},"}},SGear_UUID:[I;-1034476349,1732199694,-1735439662,280902702]}')
    )
    armor('leather',
        Item.of('silentgear:helmet', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:helmet_plates",Item:{Count:1b,id:"silentgear:helmet_plates",tag:{CraftedCount:1,Damage:0,Materials:[{Count:5b,ID:"silentgear:leather",Item:{Count:1b,id:"minecraft:leather"}}]}}}]},Properties:{HarvestTier:"minecraft:wood",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:armor":1.0f,"silentgear:armor_durability":5.0f,"silentgear:armor_toughness":0.0f,"silentgear:charging_value":0.8000001f,"silentgear:durability":0.0f,"silentgear:enchantment_value":15.000001f,"silentgear:knockback_resistance":0.0f,"silentgear:magic_armor":2.0f,"silentgear:rarity":11.000001f,"silentgear:repair_efficiency":1.0f},Traits:[]},Rendering:{Model:2,ModelKey:"helmet:helmet_plates{leather,leather,leather,leather,leather},"}},SGear_UUID:[I;120346723,1471431243,-1219029032,173985935]}'),
        Item.of('silentgear:chestplate', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:chestplate_plates",Item:{Count:1b,id:"silentgear:chestplate_plates",tag:{CraftedCount:1,Damage:0,Materials:[{Count:8b,ID:"silentgear:leather",Item:{Count:1b,id:"minecraft:leather"}}]}}}]},Properties:{HarvestTier:"minecraft:wood",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:armor":2.9999998f,"silentgear:armor_durability":5.0f,"silentgear:armor_toughness":0.0f,"silentgear:charging_value":0.8f,"silentgear:durability":0.0f,"silentgear:enchantment_value":15.0f,"silentgear:knockback_resistance":0.0f,"silentgear:magic_armor":2.0f,"silentgear:rarity":11.0f,"silentgear:repair_efficiency":1.0f},Traits:[]},Rendering:{Model:2,ModelKey:"chestplate:chestplate_plates{leather,leather,leather,leather,leather,leather,leather,leather},"}},SGear_UUID:[I;-414582085,-805616718,-1321134012,-2125049607]}'),
        Item.of('silentgear:leggings', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:legging_plates",Item:{Count:1b,id:"silentgear:legging_plates",tag:{CraftedCount:1,Damage:0,Materials:[{Count:7b,ID:"silentgear:leather",Item:{Count:1b,id:"minecraft:leather"}}]}}}]},Properties:{HarvestTier:"minecraft:wood",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:armor":2.0f,"silentgear:armor_durability":5.0f,"silentgear:armor_toughness":0.0f,"silentgear:charging_value":0.8f,"silentgear:durability":0.0f,"silentgear:enchantment_value":15.000001f,"silentgear:knockback_resistance":0.0f,"silentgear:magic_armor":2.0f,"silentgear:rarity":11.0f,"silentgear:repair_efficiency":1.0f},Traits:[]},Rendering:{Model:2,ModelKey:"leggings:legging_plates{leather,leather,leather,leather,leather,leather,leather},"}},SGear_UUID:[I;-1027851084,1914063770,-1836706143,-1690437952]}'),
        Item.of('silentgear:boots', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:boot_plates",Item:{Count:1b,id:"silentgear:boot_plates",tag:{CraftedCount:1,Damage:0,Materials:[{Count:4b,ID:"silentgear:leather",Item:{Count:1b,id:"minecraft:leather"}}]}}}]},Properties:{HarvestTier:"minecraft:wood",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:armor":1.0f,"silentgear:armor_durability":5.0f,"silentgear:armor_toughness":0.0f,"silentgear:charging_value":0.8f,"silentgear:durability":0.0f,"silentgear:enchantment_value":15.000001f,"silentgear:knockback_resistance":0.0f,"silentgear:magic_armor":2.0f,"silentgear:rarity":11.000001f,"silentgear:repair_efficiency":1.0f},Traits:[{Level:1b,Name:"silentgear:snow_walker"}]},Rendering:{Model:2,ModelKey:"boots:boot_plates{leather,leather,leather,leather},"}},SGear_UUID:[I;-764087874,-1150858821,-2050615959,1223520764]}')
    )
    e.replaceOutput({id: 'shears'}, 'shears', Item.of('silentgear:shears', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:shears_blades",Item:{Count:1b,id:"silentgear:shears_blades",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:iron",Item:{Count:1b,id:"minecraft:iron_ingot"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:iron",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":0.0f,"silentgear:charging_value":0.6999999f,"silentgear:durability":237.99998f,"silentgear:enchantment_value":13.999999f,"silentgear:harvest_speed":5.9999995f,"silentgear:magic_damage":1.0f,"silentgear:melee_damage":2.0f,"silentgear:rarity":20.0f,"silentgear:repair_efficiency":1.25f},Traits:[{Level:3b,Name:"silentgear:malleable"},{Level:1b,Name:"silentgear:magnetic"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:3,ModelKey:"shears:shears_blades{iron,iron},rod{wood},"}},SGear_UUID:[I;-305546813,-2032975004,-2030148494,-1337803403]}'))
    e.replaceOutput({id: 'fishing_rod'}, 'fishing_rod', Item.of('silentgear:fishing_rod', '{Damage:0,SGear_Data:{Construction:{Parts:[{ID:"silentgear:fishing_reel_and_hook",Item:{Count:1b,id:"silentgear:fishing_reel_and_hook",tag:{CraftedCount:1,Damage:0,Materials:[{Count:2b,ID:"silentgear:wood/oak",Item:{Count:1b,id:"minecraft:oak_planks"}}]}}},{ID:"silentgear:bowstring",Item:{Count:1b,id:"silentgear:cord",tag:{CraftedCount:1,Materials:[{Count:3b,ID:"silentgear:string",Item:{Count:1b,id:"minecraft:string"}}]}}},{ID:"silentgear:rod",Item:{Count:1b,id:"silentgear:rod",tag:{Materials:[{ID:"silentgear:wood",Item:{Count:1b,id:"minecraft:mangrove_planks",tag:{}}}]}}}]},Properties:{HarvestTier:"minecraft:wood",LockStats:0b,ModVersion:"3.6.6",Stats:{"silentgear:attack_reach":3.0f,"silentgear:attack_speed":0.0f,"silentgear:charging_value":0.6f,"silentgear:durability":29.499998f,"silentgear:enchantment_value":3.75f,"silentgear:melee_damage":0.0f,"silentgear:rarity":1.0f,"silentgear:repair_efficiency":1.25f},Traits:[{Level:1b,Name:"silentgear:flammable"},{Level:1b,Name:"silentgear:jagged"},{Level:2b,Name:"silentgear:flexible"}]},Rendering:{Model:2,ModelKey:"fishing_rod:fishing_reel_and_hook{wood/oak,wood/oak},bowstring{string,string,string},rod{wood},"}},SGear_UUID:[I;-1354359120,-1197453915,-1516564003,1983297799]}'))

    function template(type, input) {
        e.remove({output: `silentgear:${type}_template`})
        e.remove({output: `silentgear:${type}_blueprint`})
        e.shapeless(`silentgear:${type}_template`, ['silentgear:template_board', input]).keepIngredient(input)
        e.shapeless(`silentgear:${type}_blueprint`, ['silentgear:blueprint_paper', input]).keepIngredient(input)
    }

    template('rod', '#forge:rods')
    template('fletching', '#forge:feathers')
    template('sword', '#swords')

})